name: 'publish'
on:
  push:
    branches:
      - main
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'Plover v__VERSION__'
          releaseBody: |
            # Plover v__VERSION__ Release

            PRE-ALPHA WE AINT EVEN GOT ANY FEATURES IN HERE YET IT BARELY GETS OFF THE GROUND

            ## What's New
            - IT RUNS HALLELUJIAHAH

            ## Installation Instructions

            ### Windows
            - Download the `.exe` file
            - Run the installer and follow the on-screen instructions (if there are any?? I didn't make any...)

            ### macOS
            - Download the appropriate `.dmg` file for your Mac (Intel or Apple Silicon)
            - Open the DMG file and drag the Plover app to your Applications folder

            ### Linux
            - For Ubuntu and Debian-based distributions: Download and install the `.deb` file
            - For other distributions: Use the `.AppImage` file (make it executable with `chmod +x`)

            ## Additional Information
            - For full release notes and documentation, visit our [GitHub repository](https://github.com/Mumflrr/plover)
            - Report any issues or provide feedback on our [Issues page](https://github.com/Mumflrr/plover/issues)

            Thank you for using Plover! We hope you enjoy this new release. Or don't. Honestly I wouldn't.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
